version: "3.9"

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb-iaq  # Changed container name
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescale-iaq-data:/var/lib/postgresql/data  # Different volume name

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-iaq  # Changed container name
    ports: 
      - "3001:3000"

volumes:
  timescale-iaq-data:  # Different volume name